from google import genai
from dotenv import load_dotenv
import os

load_dotenv()
API_KEY = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=API_KEY)

def generate_ai_report(total_transactions, high_risk, medium_risk, safe, average_risk, highest_risk, lowest_risk, reason_summary, high_risk_transactions):
    prompt = f"""
You are a Senior Banking Fraud Analyst working for an international financial institution.

A rule-based fraud detection engine has already analyzed a dataset of financial transactions.

IMPORTANT:

- Do NOT calculate fraud scores.
- Do NOT modify any results.
- Do NOT invent transactions.
- Use ONLY the information provided below.

Prepare a professional Fraud Investigation Report and lebel it as "FRAUD INVESTIGATION REPORT Generated by Gemini AI"

The report must contain:

1. Executive Summary

2. Dataset Statistics

3. Risk Assessment

4. Common Fraud Indicators

5. Investigation Recommendations

6. Fraud Prevention Suggestions

7. Final Conclusion

----------------------------------------------------

Writing Guidelines:

• Use formal business English.
• Keep each section concise.
• Use clear headings in CAPITAL LETTERS.
• Avoid markdown symbols such as #, *, or -.
• Do not use emojis.
• Present statistics naturally inside the paragraphs.
• Make the report readable and well formatted.

DATASET SUMMARY

Total Transactions: {total_transactions}

High Risk Transactions: {high_risk}

Medium Risk Transactions: {medium_risk}

Safe Transactions: {safe}

Average Risk Score: {average_risk}

Highest Risk Score: {highest_risk}

Lowest Risk Score: {lowest_risk}

----------------------------------------------------

Fraud Indicator Frequency

{reason_summary}

----------------------------------------------------

High Risk Transactions

{high_risk_transactions}

----------------------------------------------------

Write the report professionally.

Use clear headings.

Keep it concise.

Presentable to a Website dashboard.

Begin the report with:

================================================

AI FRAUD INVESTIGATION REPORT

Generated by Gemini AI

================================================

finish with
============================

End of Report

"""
    

    response = client.models.generate_content(model="gemini-3.1-flash-lite", contents=prompt)

    return response.text

# if __name__ == "__main__":

#     report = generate_ai_report(

#         total_transactions=50,

#         high_risk=18,

#         medium_risk=10,

#         safe=22,

#         average_risk=84,

#         highest_risk=230,

#         lowest_risk=0,

#         reason_summary="""
# Foreign Transaction: 15
# High Transaction Amount: 10
# New Device Used: 8
# Login Attempts Exceeded: 6
# """,

#         high_risk_transactions="""
# Transaction ID: 1003
# Risk Score: 180
# Reasons: High Transaction Amount, Foreign Transaction, New Device Used

# Transaction ID: 1012
# Risk Score: 160
# Reasons: High Transaction Amount, Login Attempts Exceeded
# """
#     )

#     print(report)